import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '@/public/css/pokemon.module.css'
import TopWorks from '@/components/organisms/TopWorks'
import About from '@/components/templates/top/About'
import ContentWrap from '@/components/templates/top/ContentWrap'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Various App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:w-[100%] md:w-[80%] sm:w-[80%]">
        <div className="p-4 max-w-[1300px] mx-auto my-10">
          <ContentWrap><About /></ContentWrap>
          <ContentWrap><TopWorks /></ContentWrap>
        </div>
      </div>
    </>
  )
}
