import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Various App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-4xl font-bold mb-3">メニュー</h1>
        <div className="p-10">
          <ul className='list-disc flex gap-10'>
          </ul>
        </div>
      </div>
    </>
  )
}
